name: Cache Dependencies

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm           # Adjust this path to your dependencies folder(s)
            # You can also add other paths, e.g., ~/.cache, node_modules, etc.
          key: cache-491cc55

      - name: prime-cache-491cc55
        run: echo "Cache hit: ${{ steps.cache-deps.outputs.cache-hit }}"
